import { useMemo, useState } from 'react'
import { ArrowUpRight, Bot, Copy, MessageSquare, Plus, Rocket, Trash2 } from 'lucide-react'
import { useApp, toast } from '../store/app-store'
import { Avatar, Badge, PageHeader } from '../components/common'
import { DetailDrawer, FilterBar, MetricStrip, OsStatusBadge, ResourceTable } from '../components/expert-os'
import { useExpertOs } from '../store/expert-os-store'
import { ApprovalPendingCard } from '../components/approval-card'
import type { ExpertRecord, RunRecord } from '../types'

export function ExpertCenterPage() {
  const { navigate, openExpertEditor } = useApp()
  const { state, createDeployment, deleteExpert, duplicateExpert, testExpert, validateExpert } = useExpertOs()
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [testingId, setTestingId] = useState<string | null>(null)
  const selected = state.experts.find((item) => item.id === selectedId) ?? null
  const rows = useMemo(() => state.experts.filter((expert) => (status === 'all' || expert.status === status) && `${expert.name} ${expert.slug}`.toLowerCase().includes(query.toLowerCase())), [state.experts, query, status])
  const deployed = state.deployments.filter((item) => item.status === 'active')
  const action = async (operation: () => Promise<void>, success: string) => { try { await operation(); toast.success(success) } catch (error) { toast.error(error instanceof Error ? error.message : '操作失败') } }
  return <div className="page-container"><PageHeader title="Expert 中心" sub="管理内置与自建 Expert、版本快照和可运行 Deployment" actions={<><button className="rounded-lg border border-slate-300 bg-white px-3.5 py-2 text-[13px] font-medium text-slate-600 hover:border-blue-400 hover:text-blue-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300" onClick={() => navigate('aichat')}>打开 AiChat <ArrowUpRight className="ml-1 inline h-3.5 w-3.5" /></button><button className="rounded-lg bg-blue-600 px-3.5 py-2 text-[13px] font-medium text-white hover:bg-blue-700" onClick={() => openExpertEditor()}><Plus className="mr-1 inline h-4 w-4" />创建 Expert</button></>} />
    <MetricStrip items={[{ label: 'Expert 总数', value: state.experts.length, note: `${state.experts.filter((item) => item.kind === 'builtin').length} 个内置`, tone: 'pur' }, { label: '已发布', value: state.experts.filter((item) => item.status === 'published').length, note: '可创建 Deployment', tone: 'suc' }, { label: '测试中', value: state.experts.filter((item) => item.status === 'testing').length, note: '需要验证', tone: 'warn' }, { label: '活跃 Deployment', value: deployed.length, note: '可在 AiChat 选择', tone: 'info' }, { label: '调用成功率', value: '97.8%', note: '本地演示统计', tone: 'suc' }]} />
    <FilterBar query={query} onQueryChange={setQuery} placeholder="搜索 Expert 名称或 slug…"><select aria-label="筛选 Expert 状态" value={status} onChange={(event) => setStatus(event.target.value)} className="h-9 rounded-lg border border-slate-300 bg-white px-3 text-[12px] text-slate-600 outline-none dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300"><option value="all">全部状态</option><option value="published">已发布</option><option value="testing">测试中</option><option value="draft">草稿</option><option value="suspended">已挂起</option></select></FilterBar>
    <ResourceTable rows={rows} onRowClick={(expert) => setSelectedId(expert.id)} columns={[{ key: 'name', label: 'Expert', render: (expert) => <div className="flex min-w-[230px] items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-50 text-violet-600 dark:bg-violet-500/15"><Bot className="h-4 w-4" /></span><span><b className="block text-[13px] font-semibold text-slate-800 dark:text-slate-100">{expert.name}</b><span className="font-mono text-[10.5px] text-slate-400">{expert.slug}</span></span></div> }, { key: 'kind', label: '类型', render: (expert) => <Badge tone={expert.kind === 'builtin' ? 'info' : 'pur'}>{expert.kind === 'builtin' ? '内置' : '自建'}</Badge> }, { key: 'version', label: '当前版本', render: (expert) => <span className="font-mono text-[11.5px]">{expert.version}</span> }, { key: 'skills', label: 'Skills', render: (expert) => <span>{expert.skills.length} 个绑定</span> }, { key: 'deployments', label: 'Deployments', render: (expert) => <span>{expert.deployments || '—'}</span> }, { key: 'owner', label: '负责人', render: (expert) => <span className="inline-flex items-center gap-1.5"><Avatar name={expert.owner} grad="g5" size={18} />{expert.owner}</span> }, { key: 'status', label: '状态', render: (expert) => <OsStatusBadge status={expert.status} /> }, { key: 'updated', label: '最近更新', render: (expert) => <span className="whitespace-nowrap text-slate-400">{expert.updated}</span> }]} />
    <DetailDrawer open={!!selected} title={selected?.name ?? ''} eyebrow="Expert 详情" onClose={() => setSelectedId(null)}>{selected && <ExpertDetail expert={selected} blockers={validateExpert(selected.id, true)} onEdit={() => { setSelectedId(null); openExpertEditor(selected.id) }} onTest={() => { setSelectedId(null); setTestingId(selected.id) }} onDuplicate={() => void action(() => duplicateExpert(selected.id), '已创建草稿副本')} onDeploy={() => {
      const deployments = state.deployments.filter((item) => item.expertId === selected.id)
      const environment = deployments.length ? 'test' : 'prod'
      const baseName = `${selected.slug}-${environment}`
      const names = new Set(state.deployments.map((item) => item.name))
      let name = baseName
      let suffix = 2
      while (names.has(name)) name = `${baseName}-${suffix++}`
      return void action(() => createDeployment(selected.id, { name, environment, alias: selected.slug }), 'Deployment 已创建并固定当前版本')
    }} onDelete={() => void action(async () => { await deleteExpert(selected.id); setSelectedId(null) }, '草稿已删除')} deployments={state.deployments.filter((item) => item.expertId === selected.id)} />}</DetailDrawer>
    <TestDrawer expert={state.experts.find((item) => item.id === testingId) ?? null} onClose={() => setTestingId(null)} onRun={testExpert} onRuntime={() => navigate('runtime-center')} />
  </div>
}

function ExpertDetail({ expert, deployments, blockers, onEdit, onTest, onDuplicate, onDeploy, onDelete }: { expert: ExpertRecord; deployments: { id: string; name: string; expertVersion: string; environment: string; status: string }[]; blockers: string[]; onEdit: () => void; onTest: () => void; onDuplicate: () => void; onDeploy: () => void; onDelete: () => void }) {
  return <div className="space-y-5"><div className="flex items-start gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-violet-100 text-violet-600 dark:bg-violet-500/15"><Bot className="h-6 w-6" /></span><div><div className="flex gap-2"><OsStatusBadge status={expert.status} /><Badge tone={expert.kind === 'builtin' ? 'info' : 'pur'}>{expert.kind === 'builtin' ? '内置 Expert' : '自建 Expert'}</Badge></div><p className="mt-2 text-[12.5px] text-slate-500">{expert.description}</p></div></div><div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-[12px] dark:bg-slate-800/60"><div>当前版本 <b className="ml-1 font-mono">{expert.version}</b></div><div>所有者 <b className="ml-1">{expert.owner}</b></div><div>Deployment <b className="ml-1">{expert.deployments}</b></div><div>发布状态 <b className="ml-1">{expert.status}</b></div></div><section className={`rounded-lg border p-3 text-xs ${blockers.length ? 'border-amber-200 bg-amber-50 text-amber-800' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}><b>{blockers.length ? '发布被阻断' : '可发布'}</b>{blockers.length ? <ul className="mt-2 list-disc space-y-1 pl-4">{blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul> : <p className="mt-1">当前版本已通过全部发布检查。</p>}</section><section><h3 className="mb-2 text-sm font-semibold">Deployments</h3>{deployments.length ? <div className="space-y-2">{deployments.map((deployment) => <div key={deployment.id} className="rounded-lg border border-slate-200 px-3 py-2 text-xs dark:border-slate-700"><b>{deployment.name}</b><span className="ml-2 font-mono text-slate-400">{deployment.expertVersion}</span><span className="ml-2 text-slate-400">{deployment.environment} · {deployment.status}</span></div>)}</div> : <p className="text-xs text-slate-400">尚无 Deployment</p>}</section>{expert.kind === 'custom' ? <div className="grid grid-cols-2 gap-2"><button className="rounded-lg border border-slate-300 py-2 text-xs font-medium" onClick={onEdit}>编辑配置</button><button className="rounded-lg border border-slate-300 py-2 text-xs font-medium" onClick={onDuplicate}><Copy className="mr-1 inline h-3.5 w-3.5" />复制</button><button className="rounded-lg border border-blue-300 py-2 text-xs font-medium text-blue-600" onClick={onTest}><MessageSquare className="mr-1 inline h-3.5 w-3.5" />打开测试</button>{expert.status === 'published' && <button className="rounded-lg bg-blue-600 py-2 text-xs font-medium text-white" onClick={onDeploy}><Rocket className="mr-1 inline h-3.5 w-3.5" />创建 Deployment</button>}{expert.status === 'draft' && expert.deployments === 0 && <button className="col-span-2 rounded-lg border border-red-300 py-2 text-xs font-medium text-red-600" onClick={onDelete}><Trash2 className="mr-1 inline h-3.5 w-3.5" />删除草稿</button>}</div> : <p className="rounded-lg bg-slate-50 p-3 text-xs text-slate-500 dark:bg-slate-800">内置 Expert 为只读配置。</p>}</div>
}

function TestDrawer({ expert, onClose, onRun, onRuntime }: { expert: ExpertRecord | null; onClose: () => void; onRun: (expertId: string, prompt: string, writeIntent?: boolean) => Promise<RunRecord>; onRuntime: () => void }) {
  const [prompt, setPrompt] = useState('请用当前 Expert 配置总结这个测试请求，并说明是否需要人工审批。')
  const [writeIntent, setWriteIntent] = useState(false)
  const [busy, setBusy] = useState(false)
  const [result, setResult] = useState('')
  const [interruptedRunId, setInterruptedRunId] = useState<string | null>(null)
  if (!expert) return null
  const run = async () => { setBusy(true); setResult(''); setInterruptedRunId(null); try { const record = await onRun(expert.id, prompt, writeIntent); if (record.status === 'interrupted') setInterruptedRunId(record.id); else setResult('测试 Run 已提交，结果请在运行中心查看。') } catch (error) { setResult(error instanceof Error ? error.message : '测试失败') } finally { setBusy(false) } }
  return <DetailDrawer open title={`${expert.name} · 测试`} eyebrow="Interactive Test" onClose={onClose}><div className="space-y-5"><p className="text-sm text-slate-500">测试使用当前草稿或发布版本的真实 Provider 配置创建 LangGraph Run，不会自动写入业务数据。</p><label className="grid gap-2 text-sm font-medium">测试消息<textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={7} className="rounded-lg border border-slate-300 bg-white p-3 text-sm outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-900" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={writeIntent} onChange={(event) => setWriteIntent(event.target.checked)} />模拟受治理写入，进入审批队列</label><button className="w-full rounded-lg bg-blue-600 py-2.5 text-sm font-medium text-white disabled:opacity-50" disabled={busy || !prompt.trim()} onClick={() => void run()}>{busy ? '运行中…' : '运行测试'}</button>{interruptedRunId && <div><p className="mb-1 text-[11.5px] font-medium text-slate-500">写入动作已按治理策略中断，等待审批：</p><ApprovalPendingCard runId={interruptedRunId} /></div>}{result && <div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-600 dark:border-slate-700 dark:bg-slate-800">{result}</div>}<button className="w-full rounded-lg border border-slate-300 py-2 text-xs font-medium" onClick={onRuntime}>打开运行中心</button></div></DetailDrawer>
}
